### ISSUE TITLE
Unable to generate output from analyses or visualizations (creates empty folders)

### ISSUE THREAD

**Issue by tuataratuatarae** [NLP-Suite/NLP-Suite#1369]
When I try to run an analysis of the text for the homework, I set everything up and get to the run button, but when I click it nothing happens. The software is able to create a folder with the name of my file in the correct output directory, but no other files open and there are no files in that folder. I don't get any error messages

<img width="1356" alt="Screenshot 2024-01-25 at 9 34 23 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/b9c16162-fdec-449c-a1fb-1ffed2e8e826">
<img width="294" alt="Screenshot 2024-01-25 at 9 34 13 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/22ff3587-40a8-4ff9-a95a-07884abada7a">
<img width="1344" alt="Screenshot 2024-01-25 at 9 34 00 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/245ce15e-b215-481e-9d3d-9b6ed03d5d23">

The same thing happens when I try to use the word cloud function. Is it possible that there is something not set up correctly in the software? All of these have check marks so I didn't think so

<img width="1355" alt="Screenshot 2024-01-25 at 9 40 20 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/7c3311e0-9e5e-4ce4-a8ff-b44e36fbff47">

**Comment by Emory-NLP** [comment]
Are there any errors in command line/prompt?
Also, I would not put the output directory inside the current-stable. If, for any reason, you need to re-install the package, you would lose all your work.

**Comment by tuataratuatarae** [comment]
Thank you for the note about directory location--I have changed that!

I got this error: --------------- platform.machine()

---------------  x86_64
2024-01-25 22:03:05.268 python[34361:2228337] Warning: Expected min height of view: (<NSButton: 0x7f8af2cfc920>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
{'text/html': '        <script type="text/javascript">\n        window.PlotlyConfig = {MathJaxConfig: \'local\'};\n        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}\n        if (typeof require !== \'undefined\') {\n        require.undef("plotly");\n        requirejs.config({\n            paths: {\n                \'plotly\': [\'https://cdn.plot.ly/plotly-2.27.0.min\']\n            }\n        });\n        require([\'plotly\'], function(Plotly) {\n            window._Plotly = Plotly;\n        });\n        }\n        </script>\n        '}
2024-01-25 22:03:23.351 python[34361:2228337] Warning: Expected min height of view: (<NSButton: 0x7f8ae5639d70>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-01-25 22:03:23.352 python[34361:2228337] Warning: Expected min height of view: (<NSButton: 0x7f8ae5639a70>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/nicholaschang/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 391, in get_loc
    return self._range.index(new_key)
ValueError: 1 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nicholaschang/anaconda3/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "statistics_txt_main.py", line 126, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "statistics_txt_main.py", line 58, in run
    outputFiles = statistics_txt_util.compute_corpus_statistics(window, inputFilename, inputDir, outputDir,
  File "/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_txt_util.py", line 177, in compute_corpus_statistics
    inputDocs = IO_files_util.getFileList(inputFilename, inputDir, fileType='.txt', silent=False, configFileName=configFileName)
  File "/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/IO_files_util.py", line 322, in getFileList
    sort_order = str(a['Sort order'][1])
  File "/Users/nicholaschang/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/Users/nicholaschang/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/nicholaschang/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 393, in get_loc
    raise KeyError(key) from err
KeyError: 1

I did some preliminary googling about this error (apparently common in Macs with Big Sur) and tried a few of the suggested fixes from the internet but nothing has worked yet.

**Comment by Emory-NLP** [comment]
Bug fixed in release 4.6.1

**Comment by tuataratuatarae** [comment]
Thanks Dr. Franzosi, but unfortunately I'm still getting the same error in release 4.6.1

<img width="1357" alt="Screenshot 2024-01-25 at 10 42 22 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/8f7663e1-7ada-4ab0-a930-6d66d22c01c1">

**Comment by Emory-NLP** [comment]
The KeyError is fixed in release 4.6.2. Simon will look at the other error.

**Comment by bianshuyang** [comment]
Send me your NLP_default_IO_config.csv in `config` folder
<img width="394" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/447fde7e-8141-4ee8-a175-796726104c63">
Also show what are the files you use as a screenshot and what your options are
I was unable to currently replicate this unexpected behavior
<img width="1257" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/2edb3456-0fbd-4b14-bf21-ed405859fd1f">

**Comment by tuataratuatarae** [comment]
I was actually able to run the analysis with the 4.6.2 update. Do you still want my IO file etc?

Thanks!
Nick

**Comment by bianshuyang** [comment]
I see. @tuataratuatarae , Did I understand correctly that there is no more errors? Would you be able to describe "2 errors" as commented above by Professor?
@Emory-NLP From what I interpret, the error message is three parts. The first part is a remnant printout of the version. The second part enlists some plotly headers. Then it quotes an error with respect to the pandas, then finally such error was determined to be found in IO_Files_util. Therefore, in short, there were only 1 error, there were no more error. The reason is that there was a line that suggests `The above exception was the direct cause of the following exception:`

**Comment by tuataratuatarae** [comment]
Sorry about that--there is still an error in the terminal. I've included it below along with my config file and the screenshot from the IO menu. 
<img width="1361" alt="Screenshot 2024-01-26 at 12 42 54 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/0b497fcf-730e-4c2a-83c1-120e1b91557a">



I have included both the default I/O config file and the GUI specific one (which is the one I was actually using)
[NLP_default_IO_config.csv](https://github.com/NLP-Suite/NLP-Suite/files/14067797/NLP_default_IO_config.csv)

[statistics_txt_config.csv](https://github.com/NLP-Suite/NLP-Suite/files/14067792/statistics_txt_config.csv)



Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.7.0.json: 370kB [00:00, 67.1MB/s]
2024-01-26 12:37:49 INFO: Downloading default packages for language: en (English) ...
2024-01-26 12:37:50 INFO: File exists: /Users/nicholaschang/stanza_resources/en/default.zip
2024-01-26 12:37:53 INFO: Finished downloading models and saved to /Users/nicholaschang/stanza_resources.
{'text/html': '        <script type="text/javascript">\n        window.PlotlyConfig = {MathJaxConfig: \'local\'};\n        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}\n        if (typeof require !== \'undefined\') {\n        require.undef("plotly");\n        requirejs.config({\n            paths: {\n                \'plotly\': [\'https://cdn.plot.ly/plotly-2.27.0.min\']\n            }\n        });\n        require([\'plotly\'], function(Plotly) {\n            window._Plotly = Plotly;\n        });\n        }\n        </script>\n        '}
2024-01-26 12:37:54.742 python[36152:2358698] Warning: Expected min height of view: (<NSButton: 0x7fda340cb300>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-01-26 12:37:54.744 python[36152:2358698] Warning: Expected min height of view: (<NSButton: 0x7fda340c8bf0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


Started running document(s) statistics at 12:37.

Processing file 1/1 The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015.txt
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.7.0.json: 370kB [00:00, 38.8MB/s]
2024-01-26 12:38:00 INFO: Downloading default packages for language: en (English) ...
2024-01-26 12:38:01 INFO: File exists: /Users/nicholaschang/stanza_resources/en/default.zip
2024-01-26 12:38:05 INFO: Finished downloading models and saved to /Users/nicholaschang/stanza_resources.
2024-01-26 12:38:05 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.7.0.json: 370kB [00:00, 51.2MB/s]
2024-01-26 12:38:05 WARNING: Language en package default expects mwt, which has been added
2024-01-26 12:38:05 INFO: Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| lemma     | combined_nocharlm |
=================================

2024-01-26 12:38:05 INFO: Using device: cpu
2024-01-26 12:38:05 INFO: Loading: tokenize
2024-01-26 12:38:06 INFO: Loading: mwt
2024-01-26 12:38:06 INFO: Loading: lemma
2024-01-26 12:38:06 INFO: Done loading processors!


Finished running document(s) statistics at 12:38 taking 8 seconds.
/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



<function compute_csv_column_statistics_NoGroupBy.<locals>.<lambda> at 0x7fda1497c3a0>
/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



<function compute_csv_column_statistics_NoGroupBy.<locals>.<lambda> at 0x7fda1497c3a0>
/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



/Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/NLP-Suite-current-stable/src/statistics_csv_util.py:181: FutureWarning:

The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.



<function compute_csv_column_statistics_NoGroupBy.<locals>.<lambda> at 0x7fda1497c3a0>


Started running sentence length algorithm at 12:38.

Processing file 1/1 The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015.txt



Records in inputfile (in charts_util) 27    /Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/Homeworks/HW2/corpus_stats_The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015/NLP_sentence_length_The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015.csv


Started running line length analysis at 12:38.

Processing file 1/1 The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015.txt


Finished running line length analysis at 12:38 taking 0 seconds.



Records in inputfile (in charts_util) 7    /Users/nicholaschang/Downloads/Emory_Spring_2024/QTM446/Homeworks/HW2/corpus_stats_The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015/NLP_line_length_The Girl on the Train_Paula Hawkins_Jean Hanff Korelitz_01-30-2015.csv
2024-01-26 12:38:11.697 python[36152:2358698] Warning: Expected min height of view: (<NSButton: 0x7fda685096e0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


Opening 8 output files... Please wait...

**Comment by bianshuyang** [comment]
> Bug fixed in release 4.6.1

<img width="796" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/a13661fe-7e3b-4970-84d8-3104991816da">
As I revisited the old code of the older versions, it appears strange that this should not be a problem. Changing the sort order means we are always going to visit a "NaN" value because in file option, but not in Folder option, we would not see a sort order value.
I tested student's config file and was unable to replicate the older issue, and it appears to me that the newer version of NLP Suite may cause an error.

```
Non fatal filename error in filename separator. Error ignored.
The filename separator ' ' stored for the filenames in your corpus is not contained in the filename
   /Users/simonbian/NLP/NLP-Suite-current-stable/lib/sampleData/newspaperArticles/a.txt
You should edit the filename settings using the button 'Setup INPUT/OUTPUT configuration at the top of the GUI.
```

Whereas there exists a "4" as a locator of a date.
In fact, Nicholas, could you show me your pandas version?
It appears to me more like a package issue than a code issue: you might in terminal try these:

```
(base) simonbian@SimondeMacBook-Air Lab0 % conda activate NLP
(NLP) simonbian@SimondeMacBook-Air Lab0 % pip show pandas
Name: pandas
Version: 1.5.2
```

Further, from the logging of everything shown above I was unable to track down an issue. 
For wordcloud generation, could you see the other issues of Pillow version ? 
https://github.com/NLP-Suite/NLP-Suite/issues/1372
From the above logging, there was only some framesize issues that wouldn't impact the performance of the software. Could you write concretely which line you think is the error?

In fact in a folder of your choice, could you first activate NLP, then type:
``` pip freeze > outpipversionandpackages.txt```
and send the output file `outpipversionandpackages.txt` so I could examine?
Thanks.

**Comment by tuataratuatarae** [comment]
I was able to successfully generate the word cloud after reinstalling pillow. I still have no clue why I get an error for the corpus analysis since I am able to get the outputs without any issues. 

I'm using pandas v. 1.5.2

<img width="570" alt="Screenshot 2024-01-28 at 8 25 40 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/123476210/5f55a87a-69f5-480b-9332-46721faa6c1d">

[outpipversionandpackages.txt](https://github.com/NLP-Suite/NLP-Suite/files/14078675/outpipversionandpackages.txt)
